language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  # Install Codecov
  - pip install codecov

  - pip install -r requirements.txt

script:
  # Basically absolutely nothing
  - true

after_success:
  # Upload code coverage to Codecov
  - codecov
